version: '3.4'

services:
  testapi:
    build: ./TestApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    networks:
      - test
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - test

networks:
  test: